// src/components/Navbar.vue
<script setup>
import ThemeToggle from "./utils/ThemeToggle.vue";
import LanguageToggle from "./utils/LanguageToggle.vue";
</script>

<template>
  <div class="md:container sticky top-0 md:top-4 flex justify-center items-center m-auto z-50">
  <div class="flex justify-between w-full md:m-4 p-2 px-6 md:border border-b border-gray-600 md:rounded-full backdrop-blur-3xl bg-slate-900 bg-opacity-50 shadow-md">
    <!-- Right side (logo) -->
    <div class="">
      <img src="../assets/LogoOrange.webp" alt="Logo" class="w-12" />
    </div>
    <!-- Left side (buttons)-->
    <div class="flex justify-center items-center">
      <!-- Extras -->
      <ThemeToggle />
      <hr class="h-5 border border-solid border-l border-gray-800 mx-3 transition-opacity"/>
      <LanguageToggle />
      <!-- Contact Button-->
      <a href="#contact" class="ml-5 overflow-hidden bg-orange-600 focus:ring-4 focus:ring-orange-300 inline-flex items-center px-6 py-2 rounded-full text-white justify-center">
        <span>{{ $t("btnNav") }}</span>
      </a>
    </div>
  </div></div>
</template>

<style scoped>
/* Transição CSS personalizada */
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>

// src/components/navbar.tsx
import LanguageSwitcher from "./utils/LanguageSwitcher";
import { useLanguage } from "@/components/utils/LanguageProvider";
import ThemeToggle from "./utils/ThemeToggle";
import Image from "next/image";
import { Button } from "./ui/button";

type HeroProps = {
  context: "thumbs" | "webdev";
};

export default function Navbar({ context }: HeroProps) {
  const { t } = useLanguage();

  const portfolio = context === "webdev" ? "portfolioWebDev" : "portfolioThumbs";

  return (
    <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/80">
      <div className="container flex h-14 items-center">
        <div className="mr-4 hidden md:flex">
          <a className="mr-6 flex items-center space-x-2" href="/">
            <Image src="/assets/LogoOrange.webp" width={40} height={40} alt="Background person" priority />
          </a>
          <nav className="flex items-center space-x-6 text-sm font-medium">
            <a className="transition-colors hover:text-foreground/80 text-foreground/60" href="#about">
              {t("about")}
            </a>
            <a className="transition-colors hover:text-foreground/80 text-foreground/60" href="#projects">
              {t(portfolio)}
            </a>
          </nav>
        </div>
        <div className="flex flex-1 items-center justify-between space-x-2 md:justify-end">
          <Button className="bg-orange-500 hover:bg-orange-700">
            <a href="#contact">
              {t("contact")}
            </a>
          </Button>
          <hr className="hidden md:block h-8 border rounded-full" />
          <div className="flex items-center space-x-2 justify-end">
            <LanguageSwitcher />
            <ThemeToggle />
          </div>
        </div>
      </div>
    </header>
  );
}
